GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "BU$HI",
    "email": "bushi@j2.fr",
    "password": "Azerty123!"
}

###
GET http://localhost:3000/users/65e4d900075d7805d13210d4

###
PATCH http://localhost:3000/users/65e4d900075d7805d13210d4
Content-Type: application/json

{
    "name": "rezrz"
}

###
DELETE http://localhost:3000/users/65e4e0d5e233b3b2fb669c06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWU0ZGEwZTRjYjdiYzEzODAwMzlhOWIiLCJpYXQiOjE3MDk0OTg2MzMsImV4cCI6MTcxNzI3NDYzM30.ofM0IErBhjfLmZDc57_B3g2P1HYYwUzkS5Ojtyi6OCw

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "j5@j2.fr",
    "password": "Azerty123!"
}
